# Generated by Django 2.1.7 on 2019-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190318_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='흐으으음',
            field=models.DateTimeField(),
        ),
    ]
