# Generated by Django 2.1.7 on 2019-03-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20190318_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='흐으으음',
        ),
    ]
