# Generated by Django 2.1.7 on 2019-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_blog_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title123',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
